version: '3'

services:
 db:
   image: postgres
   container_name: controle-academico-postgress
   restart: always
   volumes:
    - pgdata:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: controle
   ports:
     - 5432:5432
   logging:
     driver: json-file
     options:
       max-size: 100m
volumes:
 pgdata:

